### ISSUE TITLE
fix: Vuex Store is not updating in the Dev Tools

### ISSUE THREAD

**Issue by Towerful** [danielroe/typed-vuex#175] opened 2020-10-26 13:40 UTC
**🐛 The bug**
Vuex store is never updated in the Vue/Vuex Dev Tools.  
mutations, actions, getters all work. The pages are reactive, and work correctly.  
However "Load state" in the Vue/Vuex devtools show the state as its initial state

**🛠️ To reproduce**
Go to the "Normal Usage" example
https://typed-vuex.roe.dev/build
Open the Web Browser section into a new window.  
Open Vue Dev tools, go to the Vuex tab, and click "Load State"

**🌈 Expected behaviour**
I would expect the submodule firstName to be set to "John" after the 500ms timeout.  
I would expect the email to be "test@email.com" after clicking the button.  
However it only shows initial state

**ℹ️ Additional context**
I'm just getting started with Typescript in Vue/Vuex/Nuxt. I initially found this in my simple experimentation, however confirming this on the given example indicates its either an issue with my dev tools, the dev tools, or the package.

**Comment by danielroe** [comment] 2020-10-26 15:56
@Towerful This is unfortunately an issue with the dev tools rather than this package. (duplicate of #108)

**Closed** 2020-10-26 15:56 UTC
Labels: bug

**Comment by Towerful** [comment] 2020-10-26 16:08
Ah, gotcha. I had read over that, but missed the "New Vuex Backend -> Enable" switch.  
This fixed it for me, so thanks for the pointer!  
I don't think I saw that in the docs, either. Might be worth adding a note to the "Getting Started" section about this
